channels:
  - plotly
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel
  - matplotlib=3.7
  - plotly::plotly=5.16
  - scikit-learn=1.3.0
  - pandas=2.0.3
  - nbformat
  - ipywidgets=8.0.7
  - optuna=3.4.0
  - h5py=3.9.0
  - scikit-image=0.22.0
  - optuna-dashboard
  - pip
  - pip:
    - cma==3.3.0
    - panda3d==1.10.13
    - opencv-python==4.8.0.76
    - git+https://github.com/mntusr/threedattack1-gltf.git
    - mlflow < 3.0.0
    - trimesh==4.0.5
    - Rtree==1.1.0
